import {Outfit} from "next/font/google";
import "./globals.css";
import Header from './_components/Header';
import Footer from "./_components/Footer";
import { UserProvider } from "./contexts/UserContext";

const inter = Outfit({ subsets: ["latin"]});

export const metadata = {
  title: "Fixn",
  description: "Generated by Fixn",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <UserProvider>
            <Header />
            {children}
            <Footer />
          </UserProvider>
        </div>
      </body>
    </html>
  );
}
