import localFont from "next/font/local";
import "./globals.css";
import Login  from "./_components/Login";
import ForgotPassword from "./_components/forgotPassword";
import SignUp from "./_components/SignUp";
import Header from './_components/Header';



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div>
          <Header />
          <Login/>
          <SignUp/>
          {/* <ForgotPassword/> */}
          {children}
        </div>
      </body>
    </html>
  );
}
